# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DeeplinkresponseInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, usecase: str=None, link: str=None, link_type: str=None):  # noqa: E501
        """DeeplinkresponseInner - a model defined in Swagger

        :param usecase: The usecase of this DeeplinkresponseInner.  # noqa: E501
        :type usecase: str
        :param link: The link of this DeeplinkresponseInner.  # noqa: E501
        :type link: str
        :param link_type: The link_type of this DeeplinkresponseInner.  # noqa: E501
        :type link_type: str
        """
        self.swagger_types = {
            'usecase': str,
            'link': str,
            'link_type': str
        }

        self.attribute_map = {
            'usecase': 'usecase',
            'link': 'link',
            'link_type': 'linkType'
        }
        self._usecase = usecase
        self._link = link
        self._link_type = link_type

    @classmethod
    def from_dict(cls, dikt) -> 'DeeplinkresponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deeplinkresponse_inner of this DeeplinkresponseInner.  # noqa: E501
        :rtype: DeeplinkresponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usecase(self) -> str:
        """Gets the usecase of this DeeplinkresponseInner.


        :return: The usecase of this DeeplinkresponseInner.
        :rtype: str
        """
        return self._usecase

    @usecase.setter
    def usecase(self, usecase: str):
        """Sets the usecase of this DeeplinkresponseInner.


        :param usecase: The usecase of this DeeplinkresponseInner.
        :type usecase: str
        """

        self._usecase = usecase

    @property
    def link(self) -> str:
        """Gets the link of this DeeplinkresponseInner.

        URL  # noqa: E501

        :return: The link of this DeeplinkresponseInner.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this DeeplinkresponseInner.

        URL  # noqa: E501

        :param link: The link of this DeeplinkresponseInner.
        :type link: str
        """

        self._link = link

    @property
    def link_type(self) -> str:
        """Gets the link_type of this DeeplinkresponseInner.

        deeplink,weburl,internalurl are enums  # noqa: E501

        :return: The link_type of this DeeplinkresponseInner.
        :rtype: str
        """
        return self._link_type

    @link_type.setter
    def link_type(self, link_type: str):
        """Sets the link_type of this DeeplinkresponseInner.

        deeplink,weburl,internalurl are enums  # noqa: E501

        :param link_type: The link_type of this DeeplinkresponseInner.
        :type link_type: str
        """

        self._link_type = link_type
