# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmailRequestMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, from_date: str=None, to_date: str=None, account_branch: str=None):  # noqa: E501
        """EmailRequestMeta - a model defined in Swagger

        :param from_date: The from_date of this EmailRequestMeta.  # noqa: E501
        :type from_date: str
        :param to_date: The to_date of this EmailRequestMeta.  # noqa: E501
        :type to_date: str
        :param account_branch: The account_branch of this EmailRequestMeta.  # noqa: E501
        :type account_branch: str
        """
        self.swagger_types = {
            'from_date': str,
            'to_date': str,
            'account_branch': str
        }

        self.attribute_map = {
            'from_date': 'fromDate',
            'to_date': 'toDate',
            'account_branch': 'accountBranch'
        }
        self._from_date = from_date
        self._to_date = to_date
        self._account_branch = account_branch

    @classmethod
    def from_dict(cls, dikt) -> 'EmailRequestMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The emailRequest_meta of this EmailRequestMeta.  # noqa: E501
        :rtype: EmailRequestMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def from_date(self) -> str:
        """Gets the from_date of this EmailRequestMeta.


        :return: The from_date of this EmailRequestMeta.
        :rtype: str
        """
        return self._from_date

    @from_date.setter
    def from_date(self, from_date: str):
        """Sets the from_date of this EmailRequestMeta.


        :param from_date: The from_date of this EmailRequestMeta.
        :type from_date: str
        """

        self._from_date = from_date

    @property
    def to_date(self) -> str:
        """Gets the to_date of this EmailRequestMeta.


        :return: The to_date of this EmailRequestMeta.
        :rtype: str
        """
        return self._to_date

    @to_date.setter
    def to_date(self, to_date: str):
        """Sets the to_date of this EmailRequestMeta.


        :param to_date: The to_date of this EmailRequestMeta.
        :type to_date: str
        """

        self._to_date = to_date

    @property
    def account_branch(self) -> str:
        """Gets the account_branch of this EmailRequestMeta.


        :return: The account_branch of this EmailRequestMeta.
        :rtype: str
        """
        return self._account_branch

    @account_branch.setter
    def account_branch(self, account_branch: str):
        """Sets the account_branch of this EmailRequestMeta.


        :param account_branch: The account_branch of this EmailRequestMeta.
        :type account_branch: str
        """

        self._account_branch = account_branch
