# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetCustomerDataPersonalBanker(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, email: str=None, mobile_number: str=None):  # noqa: E501
        """GetCustomerDataPersonalBanker - a model defined in Swagger

        :param name: The name of this GetCustomerDataPersonalBanker.  # noqa: E501
        :type name: str
        :param email: The email of this GetCustomerDataPersonalBanker.  # noqa: E501
        :type email: str
        :param mobile_number: The mobile_number of this GetCustomerDataPersonalBanker.  # noqa: E501
        :type mobile_number: str
        """
        self.swagger_types = {
            'name': str,
            'email': str,
            'mobile_number': str
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email',
            'mobile_number': 'mobileNumber'
        }
        self._name = name
        self._email = email
        self._mobile_number = mobile_number

    @classmethod
    def from_dict(cls, dikt) -> 'GetCustomerDataPersonalBanker':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetCustomerData_personalBanker of this GetCustomerDataPersonalBanker.  # noqa: E501
        :rtype: GetCustomerDataPersonalBanker
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this GetCustomerDataPersonalBanker.


        :return: The name of this GetCustomerDataPersonalBanker.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GetCustomerDataPersonalBanker.


        :param name: The name of this GetCustomerDataPersonalBanker.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this GetCustomerDataPersonalBanker.


        :return: The email of this GetCustomerDataPersonalBanker.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this GetCustomerDataPersonalBanker.


        :param email: The email of this GetCustomerDataPersonalBanker.
        :type email: str
        """

        self._email = email

    @property
    def mobile_number(self) -> str:
        """Gets the mobile_number of this GetCustomerDataPersonalBanker.


        :return: The mobile_number of this GetCustomerDataPersonalBanker.
        :rtype: str
        """
        return self._mobile_number

    @mobile_number.setter
    def mobile_number(self, mobile_number: str):
        """Sets the mobile_number of this GetCustomerDataPersonalBanker.


        :param mobile_number: The mobile_number of this GetCustomerDataPersonalBanker.
        :type mobile_number: str
        """

        self._mobile_number = mobile_number
