# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetAccountDataPersonalBankerContact(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email: str=None, mobile_number: str=None):  # noqa: E501
        """GetAccountDataPersonalBankerContact - a model defined in Swagger

        :param email: The email of this GetAccountDataPersonalBankerContact.  # noqa: E501
        :type email: str
        :param mobile_number: The mobile_number of this GetAccountDataPersonalBankerContact.  # noqa: E501
        :type mobile_number: str
        """
        self.swagger_types = {
            'email': str,
            'mobile_number': str
        }

        self.attribute_map = {
            'email': 'email',
            'mobile_number': 'mobileNumber'
        }
        self._email = email
        self._mobile_number = mobile_number

    @classmethod
    def from_dict(cls, dikt) -> 'GetAccountDataPersonalBankerContact':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getAccountData_personalBankerContact of this GetAccountDataPersonalBankerContact.  # noqa: E501
        :rtype: GetAccountDataPersonalBankerContact
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this GetAccountDataPersonalBankerContact.


        :return: The email of this GetAccountDataPersonalBankerContact.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this GetAccountDataPersonalBankerContact.


        :param email: The email of this GetAccountDataPersonalBankerContact.
        :type email: str
        """

        self._email = email

    @property
    def mobile_number(self) -> str:
        """Gets the mobile_number of this GetAccountDataPersonalBankerContact.


        :return: The mobile_number of this GetAccountDataPersonalBankerContact.
        :rtype: str
        """
        return self._mobile_number

    @mobile_number.setter
    def mobile_number(self, mobile_number: str):
        """Sets the mobile_number of this GetAccountDataPersonalBankerContact.


        :param mobile_number: The mobile_number of this GetAccountDataPersonalBankerContact.
        :type mobile_number: str
        """

        self._mobile_number = mobile_number
