# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetTransactionsReqSort(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, value: str=None):  # noqa: E501
        """GetTransactionsReqSort - a model defined in Swagger

        :param type: The type of this GetTransactionsReqSort.  # noqa: E501
        :type type: str
        :param value: The value of this GetTransactionsReqSort.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'type': str,
            'value': str
        }

        self.attribute_map = {
            'type': 'type',
            'value': 'value'
        }
        self._type = type
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'GetTransactionsReqSort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetTransactionsReq_sort of this GetTransactionsReqSort.  # noqa: E501
        :rtype: GetTransactionsReqSort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this GetTransactionsReqSort.

        amount  # noqa: E501

        :return: The type of this GetTransactionsReqSort.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this GetTransactionsReqSort.

        amount  # noqa: E501

        :param type: The type of this GetTransactionsReqSort.
        :type type: str
        """

        self._type = type

    @property
    def value(self) -> str:
        """Gets the value of this GetTransactionsReqSort.

        gt or lt  # noqa: E501

        :return: The value of this GetTransactionsReqSort.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this GetTransactionsReqSort.

        gt or lt  # noqa: E501

        :param value: The value of this GetTransactionsReqSort.
        :type value: str
        """

        self._value = value
