# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetTransactionsReqTransactionAmount(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount1: float=None, amount: object=None, currency: str=None):  # noqa: E501
        """GetTransactionsReqTransactionAmount - a model defined in Swagger

        :param amount1: The amount1 of this GetTransactionsReqTransactionAmount.  # noqa: E501
        :type amount1: float
        :param amount: The amount of this GetTransactionsReqTransactionAmount.  # noqa: E501
        :type amount: object
        :param currency: The currency of this GetTransactionsReqTransactionAmount.  # noqa: E501
        :type currency: str
        """
        self.swagger_types = {
            'amount1': float,
            'amount': object,
            'currency': str
        }

        self.attribute_map = {
            'amount1': 'amount1',
            'amount': 'amount',
            'currency': 'currency'
        }
        self._amount1 = amount1
        self._amount = amount
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'GetTransactionsReqTransactionAmount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetTransactionsReq_transactionAmount of this GetTransactionsReqTransactionAmount.  # noqa: E501
        :rtype: GetTransactionsReqTransactionAmount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount1(self) -> float:
        """Gets the amount1 of this GetTransactionsReqTransactionAmount.


        :return: The amount1 of this GetTransactionsReqTransactionAmount.
        :rtype: float
        """
        return self._amount1

    @amount1.setter
    def amount1(self, amount1: float):
        """Sets the amount1 of this GetTransactionsReqTransactionAmount.


        :param amount1: The amount1 of this GetTransactionsReqTransactionAmount.
        :type amount1: float
        """

        self._amount1 = amount1

    @property
    def amount(self) -> object:
        """Gets the amount of this GetTransactionsReqTransactionAmount.


        :return: The amount of this GetTransactionsReqTransactionAmount.
        :rtype: object
        """
        return self._amount

    @amount.setter
    def amount(self, amount: object):
        """Sets the amount of this GetTransactionsReqTransactionAmount.


        :param amount: The amount of this GetTransactionsReqTransactionAmount.
        :type amount: object
        """

        self._amount = amount

    @property
    def currency(self) -> str:
        """Gets the currency of this GetTransactionsReqTransactionAmount.


        :return: The currency of this GetTransactionsReqTransactionAmount.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this GetTransactionsReqTransactionAmount.


        :param currency: The currency of this GetTransactionsReqTransactionAmount.
        :type currency: str
        """

        self._currency = currency
