# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetAccountDataAccountsCardRestrictionsCountries(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, countrycode: str=None):  # noqa: E501
        """GetAccountDataAccountsCardRestrictionsCountries - a model defined in Swagger

        :param countrycode: The countrycode of this GetAccountDataAccountsCardRestrictionsCountries.  # noqa: E501
        :type countrycode: str
        """
        self.swagger_types = {
            'countrycode': str
        }

        self.attribute_map = {
            'countrycode': 'countrycode'
        }
        self._countrycode = countrycode

    @classmethod
    def from_dict(cls, dikt) -> 'GetAccountDataAccountsCardRestrictionsCountries':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getAccountData_accounts_cardRestrictions_countries of this GetAccountDataAccountsCardRestrictionsCountries.  # noqa: E501
        :rtype: GetAccountDataAccountsCardRestrictionsCountries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def countrycode(self) -> str:
        """Gets the countrycode of this GetAccountDataAccountsCardRestrictionsCountries.


        :return: The countrycode of this GetAccountDataAccountsCardRestrictionsCountries.
        :rtype: str
        """
        return self._countrycode

    @countrycode.setter
    def countrycode(self, countrycode: str):
        """Sets the countrycode of this GetAccountDataAccountsCardRestrictionsCountries.


        :param countrycode: The countrycode of this GetAccountDataAccountsCardRestrictionsCountries.
        :type countrycode: str
        """

        self._countrycode = countrycode
