# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.limits_response_inner_purchase_limits import LimitsResponseInnerPurchaseLimits  # noqa: F401,E501
from swagger_server.models.limits_response_inner_purchase_transactions import LimitsResponseInnerPurchaseTransactions  # noqa: F401,E501
from swagger_server import util


class LimitsResponseInnerPurchase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, limits: LimitsResponseInnerPurchaseLimits=None, transactions: LimitsResponseInnerPurchaseTransactions=None):  # noqa: E501
        """LimitsResponseInnerPurchase - a model defined in Swagger

        :param limits: The limits of this LimitsResponseInnerPurchase.  # noqa: E501
        :type limits: LimitsResponseInnerPurchaseLimits
        :param transactions: The transactions of this LimitsResponseInnerPurchase.  # noqa: E501
        :type transactions: LimitsResponseInnerPurchaseTransactions
        """
        self.swagger_types = {
            'limits': LimitsResponseInnerPurchaseLimits,
            'transactions': LimitsResponseInnerPurchaseTransactions
        }

        self.attribute_map = {
            'limits': 'limits',
            'transactions': 'transactions'
        }
        self._limits = limits
        self._transactions = transactions

    @classmethod
    def from_dict(cls, dikt) -> 'LimitsResponseInnerPurchase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The limitsResponse_inner_purchase of this LimitsResponseInnerPurchase.  # noqa: E501
        :rtype: LimitsResponseInnerPurchase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def limits(self) -> LimitsResponseInnerPurchaseLimits:
        """Gets the limits of this LimitsResponseInnerPurchase.


        :return: The limits of this LimitsResponseInnerPurchase.
        :rtype: LimitsResponseInnerPurchaseLimits
        """
        return self._limits

    @limits.setter
    def limits(self, limits: LimitsResponseInnerPurchaseLimits):
        """Sets the limits of this LimitsResponseInnerPurchase.


        :param limits: The limits of this LimitsResponseInnerPurchase.
        :type limits: LimitsResponseInnerPurchaseLimits
        """

        self._limits = limits

    @property
    def transactions(self) -> LimitsResponseInnerPurchaseTransactions:
        """Gets the transactions of this LimitsResponseInnerPurchase.


        :return: The transactions of this LimitsResponseInnerPurchase.
        :rtype: LimitsResponseInnerPurchaseTransactions
        """
        return self._transactions

    @transactions.setter
    def transactions(self, transactions: LimitsResponseInnerPurchaseTransactions):
        """Sets the transactions of this LimitsResponseInnerPurchase.


        :param transactions: The transactions of this LimitsResponseInnerPurchase.
        :type transactions: LimitsResponseInnerPurchaseTransactions
        """

        self._transactions = transactions
