# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.limits_response_inner_purchase_limits_monthly import LimitsResponseInnerPurchaseLimitsMonthly  # noqa: F401,E501
from swagger_server import util


class LimitsResponseInnerPurchaseLimits(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, monthly: LimitsResponseInnerPurchaseLimitsMonthly=None, daily: LimitsResponseInnerPurchaseLimitsMonthly=None):  # noqa: E501
        """LimitsResponseInnerPurchaseLimits - a model defined in Swagger

        :param monthly: The monthly of this LimitsResponseInnerPurchaseLimits.  # noqa: E501
        :type monthly: LimitsResponseInnerPurchaseLimitsMonthly
        :param daily: The daily of this LimitsResponseInnerPurchaseLimits.  # noqa: E501
        :type daily: LimitsResponseInnerPurchaseLimitsMonthly
        """
        self.swagger_types = {
            'monthly': LimitsResponseInnerPurchaseLimitsMonthly,
            'daily': LimitsResponseInnerPurchaseLimitsMonthly
        }

        self.attribute_map = {
            'monthly': 'monthly',
            'daily': 'daily'
        }
        self._monthly = monthly
        self._daily = daily

    @classmethod
    def from_dict(cls, dikt) -> 'LimitsResponseInnerPurchaseLimits':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The limitsResponse_inner_purchase_limits of this LimitsResponseInnerPurchaseLimits.  # noqa: E501
        :rtype: LimitsResponseInnerPurchaseLimits
        """
        return util.deserialize_model(dikt, cls)

    @property
    def monthly(self) -> LimitsResponseInnerPurchaseLimitsMonthly:
        """Gets the monthly of this LimitsResponseInnerPurchaseLimits.


        :return: The monthly of this LimitsResponseInnerPurchaseLimits.
        :rtype: LimitsResponseInnerPurchaseLimitsMonthly
        """
        return self._monthly

    @monthly.setter
    def monthly(self, monthly: LimitsResponseInnerPurchaseLimitsMonthly):
        """Sets the monthly of this LimitsResponseInnerPurchaseLimits.


        :param monthly: The monthly of this LimitsResponseInnerPurchaseLimits.
        :type monthly: LimitsResponseInnerPurchaseLimitsMonthly
        """

        self._monthly = monthly

    @property
    def daily(self) -> LimitsResponseInnerPurchaseLimitsMonthly:
        """Gets the daily of this LimitsResponseInnerPurchaseLimits.


        :return: The daily of this LimitsResponseInnerPurchaseLimits.
        :rtype: LimitsResponseInnerPurchaseLimitsMonthly
        """
        return self._daily

    @daily.setter
    def daily(self, daily: LimitsResponseInnerPurchaseLimitsMonthly):
        """Sets the daily of this LimitsResponseInnerPurchaseLimits.


        :param daily: The daily of this LimitsResponseInnerPurchaseLimits.
        :type daily: LimitsResponseInnerPurchaseLimitsMonthly
        """

        self._daily = daily
