# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.limits_response_inner_purchase_transactions_monthly import LimitsResponseInnerPurchaseTransactionsMonthly  # noqa: F401,E501
from swagger_server import util


class LimitsResponseInnerPurchaseTransactions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, monthly: LimitsResponseInnerPurchaseTransactionsMonthly=None, daily: LimitsResponseInnerPurchaseTransactionsMonthly=None):  # noqa: E501
        """LimitsResponseInnerPurchaseTransactions - a model defined in Swagger

        :param monthly: The monthly of this LimitsResponseInnerPurchaseTransactions.  # noqa: E501
        :type monthly: LimitsResponseInnerPurchaseTransactionsMonthly
        :param daily: The daily of this LimitsResponseInnerPurchaseTransactions.  # noqa: E501
        :type daily: LimitsResponseInnerPurchaseTransactionsMonthly
        """
        self.swagger_types = {
            'monthly': LimitsResponseInnerPurchaseTransactionsMonthly,
            'daily': LimitsResponseInnerPurchaseTransactionsMonthly
        }

        self.attribute_map = {
            'monthly': 'monthly',
            'daily': 'daily'
        }
        self._monthly = monthly
        self._daily = daily

    @classmethod
    def from_dict(cls, dikt) -> 'LimitsResponseInnerPurchaseTransactions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The limitsResponse_inner_purchase_transactions of this LimitsResponseInnerPurchaseTransactions.  # noqa: E501
        :rtype: LimitsResponseInnerPurchaseTransactions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def monthly(self) -> LimitsResponseInnerPurchaseTransactionsMonthly:
        """Gets the monthly of this LimitsResponseInnerPurchaseTransactions.


        :return: The monthly of this LimitsResponseInnerPurchaseTransactions.
        :rtype: LimitsResponseInnerPurchaseTransactionsMonthly
        """
        return self._monthly

    @monthly.setter
    def monthly(self, monthly: LimitsResponseInnerPurchaseTransactionsMonthly):
        """Sets the monthly of this LimitsResponseInnerPurchaseTransactions.


        :param monthly: The monthly of this LimitsResponseInnerPurchaseTransactions.
        :type monthly: LimitsResponseInnerPurchaseTransactionsMonthly
        """

        self._monthly = monthly

    @property
    def daily(self) -> LimitsResponseInnerPurchaseTransactionsMonthly:
        """Gets the daily of this LimitsResponseInnerPurchaseTransactions.


        :return: The daily of this LimitsResponseInnerPurchaseTransactions.
        :rtype: LimitsResponseInnerPurchaseTransactionsMonthly
        """
        return self._daily

    @daily.setter
    def daily(self, daily: LimitsResponseInnerPurchaseTransactionsMonthly):
        """Sets the daily of this LimitsResponseInnerPurchaseTransactions.


        :param daily: The daily of this LimitsResponseInnerPurchaseTransactions.
        :type daily: LimitsResponseInnerPurchaseTransactionsMonthly
        """

        self._daily = daily
