# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LocateProfileResponsePersonalQuestions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dob: str=None, ssn: float=None, secret_password: str=None, ld_amount: float=None, acc_number: str=None):  # noqa: E501
        """LocateProfileResponsePersonalQuestions - a model defined in Swagger

        :param dob: The dob of this LocateProfileResponsePersonalQuestions.  # noqa: E501
        :type dob: str
        :param ssn: The ssn of this LocateProfileResponsePersonalQuestions.  # noqa: E501
        :type ssn: float
        :param secret_password: The secret_password of this LocateProfileResponsePersonalQuestions.  # noqa: E501
        :type secret_password: str
        :param ld_amount: The ld_amount of this LocateProfileResponsePersonalQuestions.  # noqa: E501
        :type ld_amount: float
        :param acc_number: The acc_number of this LocateProfileResponsePersonalQuestions.  # noqa: E501
        :type acc_number: str
        """
        self.swagger_types = {
            'dob': str,
            'ssn': float,
            'secret_password': str,
            'ld_amount': float,
            'acc_number': str
        }

        self.attribute_map = {
            'dob': 'DOB',
            'ssn': 'SSN',
            'secret_password': 'SecretPassword',
            'ld_amount': 'LDAmount',
            'acc_number': 'AccNumber'
        }
        self._dob = dob
        self._ssn = ssn
        self._secret_password = secret_password
        self._ld_amount = ld_amount
        self._acc_number = acc_number

    @classmethod
    def from_dict(cls, dikt) -> 'LocateProfileResponsePersonalQuestions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The locateProfileResponse_personalQuestions of this LocateProfileResponsePersonalQuestions.  # noqa: E501
        :rtype: LocateProfileResponsePersonalQuestions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dob(self) -> str:
        """Gets the dob of this LocateProfileResponsePersonalQuestions.


        :return: The dob of this LocateProfileResponsePersonalQuestions.
        :rtype: str
        """
        return self._dob

    @dob.setter
    def dob(self, dob: str):
        """Sets the dob of this LocateProfileResponsePersonalQuestions.


        :param dob: The dob of this LocateProfileResponsePersonalQuestions.
        :type dob: str
        """

        self._dob = dob

    @property
    def ssn(self) -> float:
        """Gets the ssn of this LocateProfileResponsePersonalQuestions.


        :return: The ssn of this LocateProfileResponsePersonalQuestions.
        :rtype: float
        """
        return self._ssn

    @ssn.setter
    def ssn(self, ssn: float):
        """Sets the ssn of this LocateProfileResponsePersonalQuestions.


        :param ssn: The ssn of this LocateProfileResponsePersonalQuestions.
        :type ssn: float
        """

        self._ssn = ssn

    @property
    def secret_password(self) -> str:
        """Gets the secret_password of this LocateProfileResponsePersonalQuestions.


        :return: The secret_password of this LocateProfileResponsePersonalQuestions.
        :rtype: str
        """
        return self._secret_password

    @secret_password.setter
    def secret_password(self, secret_password: str):
        """Sets the secret_password of this LocateProfileResponsePersonalQuestions.


        :param secret_password: The secret_password of this LocateProfileResponsePersonalQuestions.
        :type secret_password: str
        """

        self._secret_password = secret_password

    @property
    def ld_amount(self) -> float:
        """Gets the ld_amount of this LocateProfileResponsePersonalQuestions.


        :return: The ld_amount of this LocateProfileResponsePersonalQuestions.
        :rtype: float
        """
        return self._ld_amount

    @ld_amount.setter
    def ld_amount(self, ld_amount: float):
        """Sets the ld_amount of this LocateProfileResponsePersonalQuestions.


        :param ld_amount: The ld_amount of this LocateProfileResponsePersonalQuestions.
        :type ld_amount: float
        """

        self._ld_amount = ld_amount

    @property
    def acc_number(self) -> str:
        """Gets the acc_number of this LocateProfileResponsePersonalQuestions.


        :return: The acc_number of this LocateProfileResponsePersonalQuestions.
        :rtype: str
        """
        return self._acc_number

    @acc_number.setter
    def acc_number(self, acc_number: str):
        """Sets the acc_number of this LocateProfileResponsePersonalQuestions.


        :param acc_number: The acc_number of this LocateProfileResponsePersonalQuestions.
        :type acc_number: str
        """

        self._acc_number = acc_number
