# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Newuserpinrules(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source_pin: str=None):  # noqa: E501
        """Newuserpinrules - a model defined in Swagger

        :param source_pin: The source_pin of this Newuserpinrules.  # noqa: E501
        :type source_pin: str
        """
        self.swagger_types = {
            'source_pin': str
        }

        self.attribute_map = {
            'source_pin': 'sourcePin'
        }
        self._source_pin = source_pin

    @classmethod
    def from_dict(cls, dikt) -> 'Newuserpinrules':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newuserpinrules of this Newuserpinrules.  # noqa: E501
        :rtype: Newuserpinrules
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_pin(self) -> str:
        """Gets the source_pin of this Newuserpinrules.


        :return: The source_pin of this Newuserpinrules.
        :rtype: str
        """
        return self._source_pin

    @source_pin.setter
    def source_pin(self, source_pin: str):
        """Sets the source_pin of this Newuserpinrules.


        :param source_pin: The source_pin of this Newuserpinrules.
        :type source_pin: str
        """

        self._source_pin = source_pin
