# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestStatusResponseInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, account_name: str=None, account_number: str=None, customer_id: float=None, description: str=None, estimation: float=None, modify_date: float=None, request_date: float=None, request_id: str=None, request_sub_type: str=None, request_type: str=None, status: str=None):  # noqa: E501
        """RequestStatusResponseInner - a model defined in Swagger

        :param account_name: The account_name of this RequestStatusResponseInner.  # noqa: E501
        :type account_name: str
        :param account_number: The account_number of this RequestStatusResponseInner.  # noqa: E501
        :type account_number: str
        :param customer_id: The customer_id of this RequestStatusResponseInner.  # noqa: E501
        :type customer_id: float
        :param description: The description of this RequestStatusResponseInner.  # noqa: E501
        :type description: str
        :param estimation: The estimation of this RequestStatusResponseInner.  # noqa: E501
        :type estimation: float
        :param modify_date: The modify_date of this RequestStatusResponseInner.  # noqa: E501
        :type modify_date: float
        :param request_date: The request_date of this RequestStatusResponseInner.  # noqa: E501
        :type request_date: float
        :param request_id: The request_id of this RequestStatusResponseInner.  # noqa: E501
        :type request_id: str
        :param request_sub_type: The request_sub_type of this RequestStatusResponseInner.  # noqa: E501
        :type request_sub_type: str
        :param request_type: The request_type of this RequestStatusResponseInner.  # noqa: E501
        :type request_type: str
        :param status: The status of this RequestStatusResponseInner.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'account_name': str,
            'account_number': str,
            'customer_id': float,
            'description': str,
            'estimation': float,
            'modify_date': float,
            'request_date': float,
            'request_id': str,
            'request_sub_type': str,
            'request_type': str,
            'status': str
        }

        self.attribute_map = {
            'account_name': 'accountName',
            'account_number': 'accountNumber',
            'customer_id': 'customerId',
            'description': 'description',
            'estimation': 'estimation',
            'modify_date': 'modifyDate',
            'request_date': 'requestDate',
            'request_id': 'requestId',
            'request_sub_type': 'requestSubType',
            'request_type': 'requestType',
            'status': 'status'
        }
        self._account_name = account_name
        self._account_number = account_number
        self._customer_id = customer_id
        self._description = description
        self._estimation = estimation
        self._modify_date = modify_date
        self._request_date = request_date
        self._request_id = request_id
        self._request_sub_type = request_sub_type
        self._request_type = request_type
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'RequestStatusResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The requestStatusResponse_inner of this RequestStatusResponseInner.  # noqa: E501
        :rtype: RequestStatusResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account_name(self) -> str:
        """Gets the account_name of this RequestStatusResponseInner.


        :return: The account_name of this RequestStatusResponseInner.
        :rtype: str
        """
        return self._account_name

    @account_name.setter
    def account_name(self, account_name: str):
        """Sets the account_name of this RequestStatusResponseInner.


        :param account_name: The account_name of this RequestStatusResponseInner.
        :type account_name: str
        """

        self._account_name = account_name

    @property
    def account_number(self) -> str:
        """Gets the account_number of this RequestStatusResponseInner.


        :return: The account_number of this RequestStatusResponseInner.
        :rtype: str
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number: str):
        """Sets the account_number of this RequestStatusResponseInner.


        :param account_number: The account_number of this RequestStatusResponseInner.
        :type account_number: str
        """

        self._account_number = account_number

    @property
    def customer_id(self) -> float:
        """Gets the customer_id of this RequestStatusResponseInner.


        :return: The customer_id of this RequestStatusResponseInner.
        :rtype: float
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: float):
        """Sets the customer_id of this RequestStatusResponseInner.


        :param customer_id: The customer_id of this RequestStatusResponseInner.
        :type customer_id: float
        """

        self._customer_id = customer_id

    @property
    def description(self) -> str:
        """Gets the description of this RequestStatusResponseInner.


        :return: The description of this RequestStatusResponseInner.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this RequestStatusResponseInner.


        :param description: The description of this RequestStatusResponseInner.
        :type description: str
        """

        self._description = description

    @property
    def estimation(self) -> float:
        """Gets the estimation of this RequestStatusResponseInner.


        :return: The estimation of this RequestStatusResponseInner.
        :rtype: float
        """
        return self._estimation

    @estimation.setter
    def estimation(self, estimation: float):
        """Sets the estimation of this RequestStatusResponseInner.


        :param estimation: The estimation of this RequestStatusResponseInner.
        :type estimation: float
        """

        self._estimation = estimation

    @property
    def modify_date(self) -> float:
        """Gets the modify_date of this RequestStatusResponseInner.


        :return: The modify_date of this RequestStatusResponseInner.
        :rtype: float
        """
        return self._modify_date

    @modify_date.setter
    def modify_date(self, modify_date: float):
        """Sets the modify_date of this RequestStatusResponseInner.


        :param modify_date: The modify_date of this RequestStatusResponseInner.
        :type modify_date: float
        """

        self._modify_date = modify_date

    @property
    def request_date(self) -> float:
        """Gets the request_date of this RequestStatusResponseInner.


        :return: The request_date of this RequestStatusResponseInner.
        :rtype: float
        """
        return self._request_date

    @request_date.setter
    def request_date(self, request_date: float):
        """Sets the request_date of this RequestStatusResponseInner.


        :param request_date: The request_date of this RequestStatusResponseInner.
        :type request_date: float
        """

        self._request_date = request_date

    @property
    def request_id(self) -> str:
        """Gets the request_id of this RequestStatusResponseInner.


        :return: The request_id of this RequestStatusResponseInner.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this RequestStatusResponseInner.


        :param request_id: The request_id of this RequestStatusResponseInner.
        :type request_id: str
        """

        self._request_id = request_id

    @property
    def request_sub_type(self) -> str:
        """Gets the request_sub_type of this RequestStatusResponseInner.


        :return: The request_sub_type of this RequestStatusResponseInner.
        :rtype: str
        """
        return self._request_sub_type

    @request_sub_type.setter
    def request_sub_type(self, request_sub_type: str):
        """Sets the request_sub_type of this RequestStatusResponseInner.


        :param request_sub_type: The request_sub_type of this RequestStatusResponseInner.
        :type request_sub_type: str
        """

        self._request_sub_type = request_sub_type

    @property
    def request_type(self) -> str:
        """Gets the request_type of this RequestStatusResponseInner.


        :return: The request_type of this RequestStatusResponseInner.
        :rtype: str
        """
        return self._request_type

    @request_type.setter
    def request_type(self, request_type: str):
        """Sets the request_type of this RequestStatusResponseInner.


        :param request_type: The request_type of this RequestStatusResponseInner.
        :type request_type: str
        """

        self._request_type = request_type

    @property
    def status(self) -> str:
        """Gets the status of this RequestStatusResponseInner.


        :return: The status of this RequestStatusResponseInner.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this RequestStatusResponseInner.


        :param status: The status of this RequestStatusResponseInner.
        :type status: str
        """

        self._status = status
