# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.savepinreq_profile_info import SavepinreqProfileInfo  # noqa: F401,E501
from swagger_server import util


class Savepinreq(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pin: str=None, profile_info: SavepinreqProfileInfo=None):  # noqa: E501
        """Savepinreq - a model defined in Swagger

        :param pin: The pin of this Savepinreq.  # noqa: E501
        :type pin: str
        :param profile_info: The profile_info of this Savepinreq.  # noqa: E501
        :type profile_info: SavepinreqProfileInfo
        """
        self.swagger_types = {
            'pin': str,
            'profile_info': SavepinreqProfileInfo
        }

        self.attribute_map = {
            'pin': 'pin',
            'profile_info': 'profileInfo'
        }
        self._pin = pin
        self._profile_info = profile_info

    @classmethod
    def from_dict(cls, dikt) -> 'Savepinreq':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The savepinreq of this Savepinreq.  # noqa: E501
        :rtype: Savepinreq
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pin(self) -> str:
        """Gets the pin of this Savepinreq.


        :return: The pin of this Savepinreq.
        :rtype: str
        """
        return self._pin

    @pin.setter
    def pin(self, pin: str):
        """Sets the pin of this Savepinreq.


        :param pin: The pin of this Savepinreq.
        :type pin: str
        """

        self._pin = pin

    @property
    def profile_info(self) -> SavepinreqProfileInfo:
        """Gets the profile_info of this Savepinreq.


        :return: The profile_info of this Savepinreq.
        :rtype: SavepinreqProfileInfo
        """
        return self._profile_info

    @profile_info.setter
    def profile_info(self, profile_info: SavepinreqProfileInfo):
        """Sets the profile_info of this Savepinreq.


        :param profile_info: The profile_info of this Savepinreq.
        :type profile_info: SavepinreqProfileInfo
        """

        self._profile_info = profile_info
