# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StatementResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, statement_link: str=None):  # noqa: E501
        """StatementResponse - a model defined in Swagger

        :param statement_link: The statement_link of this StatementResponse.  # noqa: E501
        :type statement_link: str
        """
        self.swagger_types = {
            'statement_link': str
        }

        self.attribute_map = {
            'statement_link': 'statementLink'
        }
        self._statement_link = statement_link

    @classmethod
    def from_dict(cls, dikt) -> 'StatementResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The statementResponse of this StatementResponse.  # noqa: E501
        :rtype: StatementResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def statement_link(self) -> str:
        """Gets the statement_link of this StatementResponse.


        :return: The statement_link of this StatementResponse.
        :rtype: str
        """
        return self._statement_link

    @statement_link.setter
    def statement_link(self, statement_link: str):
        """Sets the statement_link of this StatementResponse.


        :param statement_link: The statement_link of this StatementResponse.
        :type statement_link: str
        """

        self._statement_link = statement_link
