# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Statementbody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, account_number: List[str]=None):  # noqa: E501
        """Statementbody - a model defined in Swagger

        :param account_number: The account_number of this Statementbody.  # noqa: E501
        :type account_number: List[str]
        """
        self.swagger_types = {
            'account_number': List[str]
        }

        self.attribute_map = {
            'account_number': 'accountNumber'
        }
        self._account_number = account_number

    @classmethod
    def from_dict(cls, dikt) -> 'Statementbody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The statementbody of this Statementbody.  # noqa: E501
        :rtype: Statementbody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account_number(self) -> List[str]:
        """Gets the account_number of this Statementbody.


        :return: The account_number of this Statementbody.
        :rtype: List[str]
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number: List[str]):
        """Sets the account_number of this Statementbody.


        :param account_number: The account_number of this Statementbody.
        :type account_number: List[str]
        """
        if account_number is None:
            raise ValueError("Invalid value for `account_number`, must not be `None`")  # noqa: E501

        self._account_number = account_number
