# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.transfer_recurring_add_request_recurring_options_frequency import TransferRecurringAddRequestRecurringOptionsFrequency  # noqa: F401,E501
from swagger_server import util


class TransferRecurringAddRequestRecurringOptions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount_type: str=None, frequency: TransferRecurringAddRequestRecurringOptionsFrequency=None):  # noqa: E501
        """TransferRecurringAddRequestRecurringOptions - a model defined in Swagger

        :param amount_type: The amount_type of this TransferRecurringAddRequestRecurringOptions.  # noqa: E501
        :type amount_type: str
        :param frequency: The frequency of this TransferRecurringAddRequestRecurringOptions.  # noqa: E501
        :type frequency: TransferRecurringAddRequestRecurringOptionsFrequency
        """
        self.swagger_types = {
            'amount_type': str,
            'frequency': TransferRecurringAddRequestRecurringOptionsFrequency
        }

        self.attribute_map = {
            'amount_type': 'amountType',
            'frequency': 'frequency'
        }
        self._amount_type = amount_type
        self._frequency = frequency

    @classmethod
    def from_dict(cls, dikt) -> 'TransferRecurringAddRequestRecurringOptions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transferRecurringAddRequest_recurringOptions of this TransferRecurringAddRequestRecurringOptions.  # noqa: E501
        :rtype: TransferRecurringAddRequestRecurringOptions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount_type(self) -> str:
        """Gets the amount_type of this TransferRecurringAddRequestRecurringOptions.


        :return: The amount_type of this TransferRecurringAddRequestRecurringOptions.
        :rtype: str
        """
        return self._amount_type

    @amount_type.setter
    def amount_type(self, amount_type: str):
        """Sets the amount_type of this TransferRecurringAddRequestRecurringOptions.


        :param amount_type: The amount_type of this TransferRecurringAddRequestRecurringOptions.
        :type amount_type: str
        """

        self._amount_type = amount_type

    @property
    def frequency(self) -> TransferRecurringAddRequestRecurringOptionsFrequency:
        """Gets the frequency of this TransferRecurringAddRequestRecurringOptions.


        :return: The frequency of this TransferRecurringAddRequestRecurringOptions.
        :rtype: TransferRecurringAddRequestRecurringOptionsFrequency
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: TransferRecurringAddRequestRecurringOptionsFrequency):
        """Sets the frequency of this TransferRecurringAddRequestRecurringOptions.


        :param frequency: The frequency of this TransferRecurringAddRequestRecurringOptions.
        :type frequency: TransferRecurringAddRequestRecurringOptionsFrequency
        """

        self._frequency = frequency
