# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransferScheduleListResponseSub(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, customer_id: float=None, amount: float=None, source_account_number: str=None, target_account_number: str=None, due_date: str=None, invoice_number: float=None, currency: str=None, status: str=None, scheduled_date: float=None, next_schedule_date: float=None, id: str=None):  # noqa: E501
        """TransferScheduleListResponseSub - a model defined in Swagger

        :param type: The type of this TransferScheduleListResponseSub.  # noqa: E501
        :type type: str
        :param customer_id: The customer_id of this TransferScheduleListResponseSub.  # noqa: E501
        :type customer_id: float
        :param amount: The amount of this TransferScheduleListResponseSub.  # noqa: E501
        :type amount: float
        :param source_account_number: The source_account_number of this TransferScheduleListResponseSub.  # noqa: E501
        :type source_account_number: str
        :param target_account_number: The target_account_number of this TransferScheduleListResponseSub.  # noqa: E501
        :type target_account_number: str
        :param due_date: The due_date of this TransferScheduleListResponseSub.  # noqa: E501
        :type due_date: str
        :param invoice_number: The invoice_number of this TransferScheduleListResponseSub.  # noqa: E501
        :type invoice_number: float
        :param currency: The currency of this TransferScheduleListResponseSub.  # noqa: E501
        :type currency: str
        :param status: The status of this TransferScheduleListResponseSub.  # noqa: E501
        :type status: str
        :param scheduled_date: The scheduled_date of this TransferScheduleListResponseSub.  # noqa: E501
        :type scheduled_date: float
        :param next_schedule_date: The next_schedule_date of this TransferScheduleListResponseSub.  # noqa: E501
        :type next_schedule_date: float
        :param id: The id of this TransferScheduleListResponseSub.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'type': str,
            'customer_id': float,
            'amount': float,
            'source_account_number': str,
            'target_account_number': str,
            'due_date': str,
            'invoice_number': float,
            'currency': str,
            'status': str,
            'scheduled_date': float,
            'next_schedule_date': float,
            'id': str
        }

        self.attribute_map = {
            'type': 'Type',
            'customer_id': 'CustomerId',
            'amount': 'Amount',
            'source_account_number': 'SourceAccountNumber',
            'target_account_number': 'TargetAccountNumber',
            'due_date': 'DueDate',
            'invoice_number': 'InvoiceNumber',
            'currency': 'Currency',
            'status': 'Status',
            'scheduled_date': 'ScheduledDate',
            'next_schedule_date': 'NextScheduleDate',
            'id': 'id'
        }
        self._type = type
        self._customer_id = customer_id
        self._amount = amount
        self._source_account_number = source_account_number
        self._target_account_number = target_account_number
        self._due_date = due_date
        self._invoice_number = invoice_number
        self._currency = currency
        self._status = status
        self._scheduled_date = scheduled_date
        self._next_schedule_date = next_schedule_date
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'TransferScheduleListResponseSub':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transferScheduleListResponse_sub of this TransferScheduleListResponseSub.  # noqa: E501
        :rtype: TransferScheduleListResponseSub
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this TransferScheduleListResponseSub.


        :return: The type of this TransferScheduleListResponseSub.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this TransferScheduleListResponseSub.


        :param type: The type of this TransferScheduleListResponseSub.
        :type type: str
        """

        self._type = type

    @property
    def customer_id(self) -> float:
        """Gets the customer_id of this TransferScheduleListResponseSub.


        :return: The customer_id of this TransferScheduleListResponseSub.
        :rtype: float
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: float):
        """Sets the customer_id of this TransferScheduleListResponseSub.


        :param customer_id: The customer_id of this TransferScheduleListResponseSub.
        :type customer_id: float
        """

        self._customer_id = customer_id

    @property
    def amount(self) -> float:
        """Gets the amount of this TransferScheduleListResponseSub.


        :return: The amount of this TransferScheduleListResponseSub.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this TransferScheduleListResponseSub.


        :param amount: The amount of this TransferScheduleListResponseSub.
        :type amount: float
        """

        self._amount = amount

    @property
    def source_account_number(self) -> str:
        """Gets the source_account_number of this TransferScheduleListResponseSub.


        :return: The source_account_number of this TransferScheduleListResponseSub.
        :rtype: str
        """
        return self._source_account_number

    @source_account_number.setter
    def source_account_number(self, source_account_number: str):
        """Sets the source_account_number of this TransferScheduleListResponseSub.


        :param source_account_number: The source_account_number of this TransferScheduleListResponseSub.
        :type source_account_number: str
        """

        self._source_account_number = source_account_number

    @property
    def target_account_number(self) -> str:
        """Gets the target_account_number of this TransferScheduleListResponseSub.


        :return: The target_account_number of this TransferScheduleListResponseSub.
        :rtype: str
        """
        return self._target_account_number

    @target_account_number.setter
    def target_account_number(self, target_account_number: str):
        """Sets the target_account_number of this TransferScheduleListResponseSub.


        :param target_account_number: The target_account_number of this TransferScheduleListResponseSub.
        :type target_account_number: str
        """

        self._target_account_number = target_account_number

    @property
    def due_date(self) -> str:
        """Gets the due_date of this TransferScheduleListResponseSub.


        :return: The due_date of this TransferScheduleListResponseSub.
        :rtype: str
        """
        return self._due_date

    @due_date.setter
    def due_date(self, due_date: str):
        """Sets the due_date of this TransferScheduleListResponseSub.


        :param due_date: The due_date of this TransferScheduleListResponseSub.
        :type due_date: str
        """

        self._due_date = due_date

    @property
    def invoice_number(self) -> float:
        """Gets the invoice_number of this TransferScheduleListResponseSub.


        :return: The invoice_number of this TransferScheduleListResponseSub.
        :rtype: float
        """
        return self._invoice_number

    @invoice_number.setter
    def invoice_number(self, invoice_number: float):
        """Sets the invoice_number of this TransferScheduleListResponseSub.


        :param invoice_number: The invoice_number of this TransferScheduleListResponseSub.
        :type invoice_number: float
        """

        self._invoice_number = invoice_number

    @property
    def currency(self) -> str:
        """Gets the currency of this TransferScheduleListResponseSub.


        :return: The currency of this TransferScheduleListResponseSub.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this TransferScheduleListResponseSub.


        :param currency: The currency of this TransferScheduleListResponseSub.
        :type currency: str
        """

        self._currency = currency

    @property
    def status(self) -> str:
        """Gets the status of this TransferScheduleListResponseSub.


        :return: The status of this TransferScheduleListResponseSub.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this TransferScheduleListResponseSub.


        :param status: The status of this TransferScheduleListResponseSub.
        :type status: str
        """

        self._status = status

    @property
    def scheduled_date(self) -> float:
        """Gets the scheduled_date of this TransferScheduleListResponseSub.


        :return: The scheduled_date of this TransferScheduleListResponseSub.
        :rtype: float
        """
        return self._scheduled_date

    @scheduled_date.setter
    def scheduled_date(self, scheduled_date: float):
        """Sets the scheduled_date of this TransferScheduleListResponseSub.


        :param scheduled_date: The scheduled_date of this TransferScheduleListResponseSub.
        :type scheduled_date: float
        """

        self._scheduled_date = scheduled_date

    @property
    def next_schedule_date(self) -> float:
        """Gets the next_schedule_date of this TransferScheduleListResponseSub.


        :return: The next_schedule_date of this TransferScheduleListResponseSub.
        :rtype: float
        """
        return self._next_schedule_date

    @next_schedule_date.setter
    def next_schedule_date(self, next_schedule_date: float):
        """Sets the next_schedule_date of this TransferScheduleListResponseSub.


        :param next_schedule_date: The next_schedule_date of this TransferScheduleListResponseSub.
        :type next_schedule_date: float
        """

        self._next_schedule_date = next_schedule_date

    @property
    def id(self) -> str:
        """Gets the id of this TransferScheduleListResponseSub.


        :return: The id of this TransferScheduleListResponseSub.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this TransferScheduleListResponseSub.


        :param id: The id of this TransferScheduleListResponseSub.
        :type id: str
        """

        self._id = id
