# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransferRecurringListResponseSubRecurringOptionsFrequencyDuration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, until_stop: str=None, until_date: str=None, number_of_payments: str=None):  # noqa: E501
        """TransferRecurringListResponseSubRecurringOptionsFrequencyDuration - a model defined in Swagger

        :param until_stop: The until_stop of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.  # noqa: E501
        :type until_stop: str
        :param until_date: The until_date of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.  # noqa: E501
        :type until_date: str
        :param number_of_payments: The number_of_payments of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.  # noqa: E501
        :type number_of_payments: str
        """
        self.swagger_types = {
            'until_stop': str,
            'until_date': str,
            'number_of_payments': str
        }

        self.attribute_map = {
            'until_stop': 'untilStop',
            'until_date': 'untilDate',
            'number_of_payments': 'numberOfPayments'
        }
        self._until_stop = until_stop
        self._until_date = until_date
        self._number_of_payments = number_of_payments

    @classmethod
    def from_dict(cls, dikt) -> 'TransferRecurringListResponseSubRecurringOptionsFrequencyDuration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transferRecurringListResponse_sub_recurringOptions_frequency_duration of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.  # noqa: E501
        :rtype: TransferRecurringListResponseSubRecurringOptionsFrequencyDuration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def until_stop(self) -> str:
        """Gets the until_stop of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.


        :return: The until_stop of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.
        :rtype: str
        """
        return self._until_stop

    @until_stop.setter
    def until_stop(self, until_stop: str):
        """Sets the until_stop of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.


        :param until_stop: The until_stop of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.
        :type until_stop: str
        """

        self._until_stop = until_stop

    @property
    def until_date(self) -> str:
        """Gets the until_date of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.


        :return: The until_date of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.
        :rtype: str
        """
        return self._until_date

    @until_date.setter
    def until_date(self, until_date: str):
        """Sets the until_date of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.


        :param until_date: The until_date of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.
        :type until_date: str
        """

        self._until_date = until_date

    @property
    def number_of_payments(self) -> str:
        """Gets the number_of_payments of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.


        :return: The number_of_payments of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.
        :rtype: str
        """
        return self._number_of_payments

    @number_of_payments.setter
    def number_of_payments(self, number_of_payments: str):
        """Sets the number_of_payments of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.


        :param number_of_payments: The number_of_payments of this TransferRecurringListResponseSubRecurringOptionsFrequencyDuration.
        :type number_of_payments: str
        """

        self._number_of_payments = number_of_payments
