# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.transfer_recurring_list_response_sub_recurring_options_frequency_duration import TransferRecurringListResponseSubRecurringOptionsFrequencyDuration  # noqa: F401,E501
from swagger_server import util


class TransferRecurringListResponseSubRecurringOptionsFrequency(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, duration: TransferRecurringListResponseSubRecurringOptionsFrequencyDuration=None, iterate: str=None):  # noqa: E501
        """TransferRecurringListResponseSubRecurringOptionsFrequency - a model defined in Swagger

        :param duration: The duration of this TransferRecurringListResponseSubRecurringOptionsFrequency.  # noqa: E501
        :type duration: TransferRecurringListResponseSubRecurringOptionsFrequencyDuration
        :param iterate: The iterate of this TransferRecurringListResponseSubRecurringOptionsFrequency.  # noqa: E501
        :type iterate: str
        """
        self.swagger_types = {
            'duration': TransferRecurringListResponseSubRecurringOptionsFrequencyDuration,
            'iterate': str
        }

        self.attribute_map = {
            'duration': 'duration',
            'iterate': 'iterate'
        }
        self._duration = duration
        self._iterate = iterate

    @classmethod
    def from_dict(cls, dikt) -> 'TransferRecurringListResponseSubRecurringOptionsFrequency':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transferRecurringListResponse_sub_recurringOptions_frequency of this TransferRecurringListResponseSubRecurringOptionsFrequency.  # noqa: E501
        :rtype: TransferRecurringListResponseSubRecurringOptionsFrequency
        """
        return util.deserialize_model(dikt, cls)

    @property
    def duration(self) -> TransferRecurringListResponseSubRecurringOptionsFrequencyDuration:
        """Gets the duration of this TransferRecurringListResponseSubRecurringOptionsFrequency.


        :return: The duration of this TransferRecurringListResponseSubRecurringOptionsFrequency.
        :rtype: TransferRecurringListResponseSubRecurringOptionsFrequencyDuration
        """
        return self._duration

    @duration.setter
    def duration(self, duration: TransferRecurringListResponseSubRecurringOptionsFrequencyDuration):
        """Sets the duration of this TransferRecurringListResponseSubRecurringOptionsFrequency.


        :param duration: The duration of this TransferRecurringListResponseSubRecurringOptionsFrequency.
        :type duration: TransferRecurringListResponseSubRecurringOptionsFrequencyDuration
        """

        self._duration = duration

    @property
    def iterate(self) -> str:
        """Gets the iterate of this TransferRecurringListResponseSubRecurringOptionsFrequency.


        :return: The iterate of this TransferRecurringListResponseSubRecurringOptionsFrequency.
        :rtype: str
        """
        return self._iterate

    @iterate.setter
    def iterate(self, iterate: str):
        """Sets the iterate of this TransferRecurringListResponseSubRecurringOptionsFrequency.


        :param iterate: The iterate of this TransferRecurringListResponseSubRecurringOptionsFrequency.
        :type iterate: str
        """

        self._iterate = iterate
