# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.transfer_recurring_update_request_recurring_options_frequency import TransferRecurringUpdateRequestRecurringOptionsFrequency  # noqa: F401,E501
from swagger_server import util


class TransferRecurringUpdateRequestRecurringOptions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount_type: str=None, frequency: TransferRecurringUpdateRequestRecurringOptionsFrequency=None, update_transfer_type: str=None):  # noqa: E501
        """TransferRecurringUpdateRequestRecurringOptions - a model defined in Swagger

        :param amount_type: The amount_type of this TransferRecurringUpdateRequestRecurringOptions.  # noqa: E501
        :type amount_type: str
        :param frequency: The frequency of this TransferRecurringUpdateRequestRecurringOptions.  # noqa: E501
        :type frequency: TransferRecurringUpdateRequestRecurringOptionsFrequency
        :param update_transfer_type: The update_transfer_type of this TransferRecurringUpdateRequestRecurringOptions.  # noqa: E501
        :type update_transfer_type: str
        """
        self.swagger_types = {
            'amount_type': str,
            'frequency': TransferRecurringUpdateRequestRecurringOptionsFrequency,
            'update_transfer_type': str
        }

        self.attribute_map = {
            'amount_type': 'amountType',
            'frequency': 'frequency',
            'update_transfer_type': 'updateTransferType'
        }
        self._amount_type = amount_type
        self._frequency = frequency
        self._update_transfer_type = update_transfer_type

    @classmethod
    def from_dict(cls, dikt) -> 'TransferRecurringUpdateRequestRecurringOptions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transferRecurringUpdateRequest_recurringOptions of this TransferRecurringUpdateRequestRecurringOptions.  # noqa: E501
        :rtype: TransferRecurringUpdateRequestRecurringOptions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount_type(self) -> str:
        """Gets the amount_type of this TransferRecurringUpdateRequestRecurringOptions.


        :return: The amount_type of this TransferRecurringUpdateRequestRecurringOptions.
        :rtype: str
        """
        return self._amount_type

    @amount_type.setter
    def amount_type(self, amount_type: str):
        """Sets the amount_type of this TransferRecurringUpdateRequestRecurringOptions.


        :param amount_type: The amount_type of this TransferRecurringUpdateRequestRecurringOptions.
        :type amount_type: str
        """

        self._amount_type = amount_type

    @property
    def frequency(self) -> TransferRecurringUpdateRequestRecurringOptionsFrequency:
        """Gets the frequency of this TransferRecurringUpdateRequestRecurringOptions.


        :return: The frequency of this TransferRecurringUpdateRequestRecurringOptions.
        :rtype: TransferRecurringUpdateRequestRecurringOptionsFrequency
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: TransferRecurringUpdateRequestRecurringOptionsFrequency):
        """Sets the frequency of this TransferRecurringUpdateRequestRecurringOptions.


        :param frequency: The frequency of this TransferRecurringUpdateRequestRecurringOptions.
        :type frequency: TransferRecurringUpdateRequestRecurringOptionsFrequency
        """

        self._frequency = frequency

    @property
    def update_transfer_type(self) -> str:
        """Gets the update_transfer_type of this TransferRecurringUpdateRequestRecurringOptions.


        :return: The update_transfer_type of this TransferRecurringUpdateRequestRecurringOptions.
        :rtype: str
        """
        return self._update_transfer_type

    @update_transfer_type.setter
    def update_transfer_type(self, update_transfer_type: str):
        """Sets the update_transfer_type of this TransferRecurringUpdateRequestRecurringOptions.


        :param update_transfer_type: The update_transfer_type of this TransferRecurringUpdateRequestRecurringOptions.
        :type update_transfer_type: str
        """

        self._update_transfer_type = update_transfer_type
