# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.transfer_recurring_list_response_sub_recurring_options_frequency import TransferRecurringListResponseSubRecurringOptionsFrequency  # noqa: F401,E501
from swagger_server import util


class TransferRecurringListResponseSubRecurringOptions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount_type: str=None, frequency: TransferRecurringListResponseSubRecurringOptionsFrequency=None):  # noqa: E501
        """TransferRecurringListResponseSubRecurringOptions - a model defined in Swagger

        :param amount_type: The amount_type of this TransferRecurringListResponseSubRecurringOptions.  # noqa: E501
        :type amount_type: str
        :param frequency: The frequency of this TransferRecurringListResponseSubRecurringOptions.  # noqa: E501
        :type frequency: TransferRecurringListResponseSubRecurringOptionsFrequency
        """
        self.swagger_types = {
            'amount_type': str,
            'frequency': TransferRecurringListResponseSubRecurringOptionsFrequency
        }

        self.attribute_map = {
            'amount_type': 'amountType',
            'frequency': 'frequency'
        }
        self._amount_type = amount_type
        self._frequency = frequency

    @classmethod
    def from_dict(cls, dikt) -> 'TransferRecurringListResponseSubRecurringOptions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transferRecurringListResponse_sub_recurringOptions of this TransferRecurringListResponseSubRecurringOptions.  # noqa: E501
        :rtype: TransferRecurringListResponseSubRecurringOptions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount_type(self) -> str:
        """Gets the amount_type of this TransferRecurringListResponseSubRecurringOptions.


        :return: The amount_type of this TransferRecurringListResponseSubRecurringOptions.
        :rtype: str
        """
        return self._amount_type

    @amount_type.setter
    def amount_type(self, amount_type: str):
        """Sets the amount_type of this TransferRecurringListResponseSubRecurringOptions.


        :param amount_type: The amount_type of this TransferRecurringListResponseSubRecurringOptions.
        :type amount_type: str
        """

        self._amount_type = amount_type

    @property
    def frequency(self) -> TransferRecurringListResponseSubRecurringOptionsFrequency:
        """Gets the frequency of this TransferRecurringListResponseSubRecurringOptions.


        :return: The frequency of this TransferRecurringListResponseSubRecurringOptions.
        :rtype: TransferRecurringListResponseSubRecurringOptionsFrequency
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: TransferRecurringListResponseSubRecurringOptionsFrequency):
        """Sets the frequency of this TransferRecurringListResponseSubRecurringOptions.


        :param frequency: The frequency of this TransferRecurringListResponseSubRecurringOptions.
        :type frequency: TransferRecurringListResponseSubRecurringOptionsFrequency
        """

        self._frequency = frequency
