# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.transfer_recurring_add_request_recurring_options_frequency_duration import TransferRecurringAddRequestRecurringOptionsFrequencyDuration  # noqa: F401,E501
from swagger_server import util


class TransferRecurringUpdateRequestRecurringOptionsFrequency(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, duration: TransferRecurringAddRequestRecurringOptionsFrequencyDuration=None, iterate: str=None):  # noqa: E501
        """TransferRecurringUpdateRequestRecurringOptionsFrequency - a model defined in Swagger

        :param duration: The duration of this TransferRecurringUpdateRequestRecurringOptionsFrequency.  # noqa: E501
        :type duration: TransferRecurringAddRequestRecurringOptionsFrequencyDuration
        :param iterate: The iterate of this TransferRecurringUpdateRequestRecurringOptionsFrequency.  # noqa: E501
        :type iterate: str
        """
        self.swagger_types = {
            'duration': TransferRecurringAddRequestRecurringOptionsFrequencyDuration,
            'iterate': str
        }

        self.attribute_map = {
            'duration': 'duration',
            'iterate': 'iterate'
        }
        self._duration = duration
        self._iterate = iterate

    @classmethod
    def from_dict(cls, dikt) -> 'TransferRecurringUpdateRequestRecurringOptionsFrequency':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transferRecurringUpdateRequest_recurringOptions_frequency of this TransferRecurringUpdateRequestRecurringOptionsFrequency.  # noqa: E501
        :rtype: TransferRecurringUpdateRequestRecurringOptionsFrequency
        """
        return util.deserialize_model(dikt, cls)

    @property
    def duration(self) -> TransferRecurringAddRequestRecurringOptionsFrequencyDuration:
        """Gets the duration of this TransferRecurringUpdateRequestRecurringOptionsFrequency.


        :return: The duration of this TransferRecurringUpdateRequestRecurringOptionsFrequency.
        :rtype: TransferRecurringAddRequestRecurringOptionsFrequencyDuration
        """
        return self._duration

    @duration.setter
    def duration(self, duration: TransferRecurringAddRequestRecurringOptionsFrequencyDuration):
        """Sets the duration of this TransferRecurringUpdateRequestRecurringOptionsFrequency.


        :param duration: The duration of this TransferRecurringUpdateRequestRecurringOptionsFrequency.
        :type duration: TransferRecurringAddRequestRecurringOptionsFrequencyDuration
        """

        self._duration = duration

    @property
    def iterate(self) -> str:
        """Gets the iterate of this TransferRecurringUpdateRequestRecurringOptionsFrequency.


        :return: The iterate of this TransferRecurringUpdateRequestRecurringOptionsFrequency.
        :rtype: str
        """
        return self._iterate

    @iterate.setter
    def iterate(self, iterate: str):
        """Sets the iterate of this TransferRecurringUpdateRequestRecurringOptionsFrequency.


        :param iterate: The iterate of this TransferRecurringUpdateRequestRecurringOptionsFrequency.
        :type iterate: str
        """

        self._iterate = iterate
