# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateCustomerRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, customer_id: float=None, email: str=None, alternate_phone_number: float=None, is_alternate_mobile_number: bool=None, phone: float=None, is_primary_mobile_number: bool=None, location: str=None):  # noqa: E501
        """UpdateCustomerRequest - a model defined in Swagger

        :param customer_id: The customer_id of this UpdateCustomerRequest.  # noqa: E501
        :type customer_id: float
        :param email: The email of this UpdateCustomerRequest.  # noqa: E501
        :type email: str
        :param alternate_phone_number: The alternate_phone_number of this UpdateCustomerRequest.  # noqa: E501
        :type alternate_phone_number: float
        :param is_alternate_mobile_number: The is_alternate_mobile_number of this UpdateCustomerRequest.  # noqa: E501
        :type is_alternate_mobile_number: bool
        :param phone: The phone of this UpdateCustomerRequest.  # noqa: E501
        :type phone: float
        :param is_primary_mobile_number: The is_primary_mobile_number of this UpdateCustomerRequest.  # noqa: E501
        :type is_primary_mobile_number: bool
        :param location: The location of this UpdateCustomerRequest.  # noqa: E501
        :type location: str
        """
        self.swagger_types = {
            'customer_id': float,
            'email': str,
            'alternate_phone_number': float,
            'is_alternate_mobile_number': bool,
            'phone': float,
            'is_primary_mobile_number': bool,
            'location': str
        }

        self.attribute_map = {
            'customer_id': 'customerId',
            'email': 'email',
            'alternate_phone_number': 'alternatePhoneNumber',
            'is_alternate_mobile_number': 'isAlternateMobileNumber',
            'phone': 'phone',
            'is_primary_mobile_number': 'isPrimaryMobileNumber',
            'location': 'location'
        }
        self._customer_id = customer_id
        self._email = email
        self._alternate_phone_number = alternate_phone_number
        self._is_alternate_mobile_number = is_alternate_mobile_number
        self._phone = phone
        self._is_primary_mobile_number = is_primary_mobile_number
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateCustomerRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The updateCustomerRequest of this UpdateCustomerRequest.  # noqa: E501
        :rtype: UpdateCustomerRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer_id(self) -> float:
        """Gets the customer_id of this UpdateCustomerRequest.


        :return: The customer_id of this UpdateCustomerRequest.
        :rtype: float
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: float):
        """Sets the customer_id of this UpdateCustomerRequest.


        :param customer_id: The customer_id of this UpdateCustomerRequest.
        :type customer_id: float
        """
        if customer_id is None:
            raise ValueError("Invalid value for `customer_id`, must not be `None`")  # noqa: E501

        self._customer_id = customer_id

    @property
    def email(self) -> str:
        """Gets the email of this UpdateCustomerRequest.


        :return: The email of this UpdateCustomerRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UpdateCustomerRequest.


        :param email: The email of this UpdateCustomerRequest.
        :type email: str
        """

        self._email = email

    @property
    def alternate_phone_number(self) -> float:
        """Gets the alternate_phone_number of this UpdateCustomerRequest.


        :return: The alternate_phone_number of this UpdateCustomerRequest.
        :rtype: float
        """
        return self._alternate_phone_number

    @alternate_phone_number.setter
    def alternate_phone_number(self, alternate_phone_number: float):
        """Sets the alternate_phone_number of this UpdateCustomerRequest.


        :param alternate_phone_number: The alternate_phone_number of this UpdateCustomerRequest.
        :type alternate_phone_number: float
        """

        self._alternate_phone_number = alternate_phone_number

    @property
    def is_alternate_mobile_number(self) -> bool:
        """Gets the is_alternate_mobile_number of this UpdateCustomerRequest.


        :return: The is_alternate_mobile_number of this UpdateCustomerRequest.
        :rtype: bool
        """
        return self._is_alternate_mobile_number

    @is_alternate_mobile_number.setter
    def is_alternate_mobile_number(self, is_alternate_mobile_number: bool):
        """Sets the is_alternate_mobile_number of this UpdateCustomerRequest.


        :param is_alternate_mobile_number: The is_alternate_mobile_number of this UpdateCustomerRequest.
        :type is_alternate_mobile_number: bool
        """

        self._is_alternate_mobile_number = is_alternate_mobile_number

    @property
    def phone(self) -> float:
        """Gets the phone of this UpdateCustomerRequest.


        :return: The phone of this UpdateCustomerRequest.
        :rtype: float
        """
        return self._phone

    @phone.setter
    def phone(self, phone: float):
        """Sets the phone of this UpdateCustomerRequest.


        :param phone: The phone of this UpdateCustomerRequest.
        :type phone: float
        """

        self._phone = phone

    @property
    def is_primary_mobile_number(self) -> bool:
        """Gets the is_primary_mobile_number of this UpdateCustomerRequest.


        :return: The is_primary_mobile_number of this UpdateCustomerRequest.
        :rtype: bool
        """
        return self._is_primary_mobile_number

    @is_primary_mobile_number.setter
    def is_primary_mobile_number(self, is_primary_mobile_number: bool):
        """Sets the is_primary_mobile_number of this UpdateCustomerRequest.


        :param is_primary_mobile_number: The is_primary_mobile_number of this UpdateCustomerRequest.
        :type is_primary_mobile_number: bool
        """

        self._is_primary_mobile_number = is_primary_mobile_number

    @property
    def location(self) -> str:
        """Gets the location of this UpdateCustomerRequest.


        :return: The location of this UpdateCustomerRequest.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this UpdateCustomerRequest.


        :param location: The location of this UpdateCustomerRequest.
        :type location: str
        """

        self._location = location
