# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VerifyOTPbody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, customer_id: float=None, code: float=None):  # noqa: E501
        """VerifyOTPbody - a model defined in Swagger

        :param customer_id: The customer_id of this VerifyOTPbody.  # noqa: E501
        :type customer_id: float
        :param code: The code of this VerifyOTPbody.  # noqa: E501
        :type code: float
        """
        self.swagger_types = {
            'customer_id': float,
            'code': float
        }

        self.attribute_map = {
            'customer_id': 'customerId',
            'code': 'code'
        }
        self._customer_id = customer_id
        self._code = code

    @classmethod
    def from_dict(cls, dikt) -> 'VerifyOTPbody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The verifyOTPbody of this VerifyOTPbody.  # noqa: E501
        :rtype: VerifyOTPbody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer_id(self) -> float:
        """Gets the customer_id of this VerifyOTPbody.


        :return: The customer_id of this VerifyOTPbody.
        :rtype: float
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: float):
        """Sets the customer_id of this VerifyOTPbody.


        :param customer_id: The customer_id of this VerifyOTPbody.
        :type customer_id: float
        """
        if customer_id is None:
            raise ValueError("Invalid value for `customer_id`, must not be `None`")  # noqa: E501

        self._customer_id = customer_id

    @property
    def code(self) -> float:
        """Gets the code of this VerifyOTPbody.


        :return: The code of this VerifyOTPbody.
        :rtype: float
        """
        return self._code

    @code.setter
    def code(self, code: float):
        """Sets the code of this VerifyOTPbody.


        :param code: The code of this VerifyOTPbody.
        :type code: float
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code
