# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ViewlimitsResponseInnerTxnsPerDay(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, available: float=None, maximum: float=None, usedup: float=None, amount: float=None):  # noqa: E501
        """ViewlimitsResponseInnerTxnsPerDay - a model defined in Swagger

        :param available: The available of this ViewlimitsResponseInnerTxnsPerDay.  # noqa: E501
        :type available: float
        :param maximum: The maximum of this ViewlimitsResponseInnerTxnsPerDay.  # noqa: E501
        :type maximum: float
        :param usedup: The usedup of this ViewlimitsResponseInnerTxnsPerDay.  # noqa: E501
        :type usedup: float
        :param amount: The amount of this ViewlimitsResponseInnerTxnsPerDay.  # noqa: E501
        :type amount: float
        """
        self.swagger_types = {
            'available': float,
            'maximum': float,
            'usedup': float,
            'amount': float
        }

        self.attribute_map = {
            'available': 'available',
            'maximum': 'maximum',
            'usedup': 'usedup',
            'amount': 'amount'
        }
        self._available = available
        self._maximum = maximum
        self._usedup = usedup
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'ViewlimitsResponseInnerTxnsPerDay':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The viewlimitsResponse_inner_txnsPerDay of this ViewlimitsResponseInnerTxnsPerDay.  # noqa: E501
        :rtype: ViewlimitsResponseInnerTxnsPerDay
        """
        return util.deserialize_model(dikt, cls)

    @property
    def available(self) -> float:
        """Gets the available of this ViewlimitsResponseInnerTxnsPerDay.


        :return: The available of this ViewlimitsResponseInnerTxnsPerDay.
        :rtype: float
        """
        return self._available

    @available.setter
    def available(self, available: float):
        """Sets the available of this ViewlimitsResponseInnerTxnsPerDay.


        :param available: The available of this ViewlimitsResponseInnerTxnsPerDay.
        :type available: float
        """

        self._available = available

    @property
    def maximum(self) -> float:
        """Gets the maximum of this ViewlimitsResponseInnerTxnsPerDay.


        :return: The maximum of this ViewlimitsResponseInnerTxnsPerDay.
        :rtype: float
        """
        return self._maximum

    @maximum.setter
    def maximum(self, maximum: float):
        """Sets the maximum of this ViewlimitsResponseInnerTxnsPerDay.


        :param maximum: The maximum of this ViewlimitsResponseInnerTxnsPerDay.
        :type maximum: float
        """

        self._maximum = maximum

    @property
    def usedup(self) -> float:
        """Gets the usedup of this ViewlimitsResponseInnerTxnsPerDay.


        :return: The usedup of this ViewlimitsResponseInnerTxnsPerDay.
        :rtype: float
        """
        return self._usedup

    @usedup.setter
    def usedup(self, usedup: float):
        """Sets the usedup of this ViewlimitsResponseInnerTxnsPerDay.


        :param usedup: The usedup of this ViewlimitsResponseInnerTxnsPerDay.
        :type usedup: float
        """

        self._usedup = usedup

    @property
    def amount(self) -> float:
        """Gets the amount of this ViewlimitsResponseInnerTxnsPerDay.


        :return: The amount of this ViewlimitsResponseInnerTxnsPerDay.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this ViewlimitsResponseInnerTxnsPerDay.


        :param amount: The amount of this ViewlimitsResponseInnerTxnsPerDay.
        :type amount: float
        """

        self._amount = amount
