# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ViewLimitRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, customer_id: float=None, account_number: List[str]=None, card_number: List[str]=None):  # noqa: E501
        """ViewLimitRequest - a model defined in Swagger

        :param customer_id: The customer_id of this ViewLimitRequest.  # noqa: E501
        :type customer_id: float
        :param account_number: The account_number of this ViewLimitRequest.  # noqa: E501
        :type account_number: List[str]
        :param card_number: The card_number of this ViewLimitRequest.  # noqa: E501
        :type card_number: List[str]
        """
        self.swagger_types = {
            'customer_id': float,
            'account_number': List[str],
            'card_number': List[str]
        }

        self.attribute_map = {
            'customer_id': 'customerId',
            'account_number': 'accountNumber',
            'card_number': 'cardNumber'
        }
        self._customer_id = customer_id
        self._account_number = account_number
        self._card_number = card_number

    @classmethod
    def from_dict(cls, dikt) -> 'ViewLimitRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The viewLimitRequest of this ViewLimitRequest.  # noqa: E501
        :rtype: ViewLimitRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer_id(self) -> float:
        """Gets the customer_id of this ViewLimitRequest.


        :return: The customer_id of this ViewLimitRequest.
        :rtype: float
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: float):
        """Sets the customer_id of this ViewLimitRequest.


        :param customer_id: The customer_id of this ViewLimitRequest.
        :type customer_id: float
        """

        self._customer_id = customer_id

    @property
    def account_number(self) -> List[str]:
        """Gets the account_number of this ViewLimitRequest.


        :return: The account_number of this ViewLimitRequest.
        :rtype: List[str]
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number: List[str]):
        """Sets the account_number of this ViewLimitRequest.


        :param account_number: The account_number of this ViewLimitRequest.
        :type account_number: List[str]
        """

        self._account_number = account_number

    @property
    def card_number(self) -> List[str]:
        """Gets the card_number of this ViewLimitRequest.


        :return: The card_number of this ViewLimitRequest.
        :rtype: List[str]
        """
        return self._card_number

    @card_number.setter
    def card_number(self, card_number: List[str]):
        """Sets the card_number of this ViewLimitRequest.


        :param card_number: The card_number of this ViewLimitRequest.
        :type card_number: List[str]
        """

        self._card_number = card_number
